<a href="https://colab.research.google.com/github/TimeKP/AI-study-contents/blob/main/factor_extracting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import pandas as pd
import numpy as np

In [141]:
coef_final = pd.read_csv('/content/drive/MyDrive/AI_bootcamp/Section2-Machine Learning/Project/coef_result/coef_final')
df_20 = pd.read_csv('/content/drive/MyDrive/AI_bootcamp/Section2-Machine Learning/Project/20nm_split.csv')

df_20 = df_20.apply(pd.to_numeric, errors='coerce')

In [142]:
df_20.head()

,Unnamed: 0,90,105,120,135,150,165,180,195,210,...,165.30,180.30,195.30,210.30,225.30,240.30,255.30,270.30,285.30,300.30
0,0,2.613001e-17,2.811053e-17,1.878294e-17,5.685993e-18,1.597189e-17,5.494330e-18,1.533301e-18,2.791886e-17,2.600224e-17,...,3.124102e-17,3.104935e-17,2.357451e-17,3.577703e-18,1.066922e-17,1.437470e-17,9.199808e-18,1.456636e-17,1.034978e-17,2.491615e-18
1,20,6.353694e-14,1.840953e-13,1.172707e-13,6.377549e-13,1.519884e-12,4.453417e-12,9.441501e-12,1.811356e-11,2.809758e-11,...,1.911957e-14,1.012855e-13,3.645545e-14,1.431145e-15,8.776892e-14,1.072634e-14,1.205586e-13,1.402537e-13,1.359591e-13,3.389610e-13
2,40,5.367660e-14,4.709618e-14,2.284855e-13,1.416110e-12,4.028117e-12,1.034724e-11,2.179590e-11,3.925168e-11,6.070183e-11,...,1.477669e-13,1.600434e-14,8.503747e-14,7.314033e-14,7.877163e-14,2.403105e-14,2.358536e-13,2.833873e-14,3.521885e-13,3.656348e-13
3,60,1.618930e-14,4.051385e-14,5.081765e-13,2.502685e-12,7.046869e-12,1.747149e-11,3.630870e-11,6.387985e-11,9.877706e-11,...,2.005279e-13,7.776464e-14,2.671856e-13,1.166883e-13,2.722676e-13,1.956542e-13,3.049058e-13,1.157033e-13,3.317678e-13,2.891222e-13
4,80,2.942292e-13,1.586130e-14,6.548843e-13,4.051417e-12,1.108677e-11,2.707363e-11,5.341664e-11,9.273135e-11,1.404630e-10,...,1.149688e-13,2.289936e-13,2.035521e-15,2.051203e-13,1.245187e-13,6.526402e-14,8.458464e-14,2.461957e-13,2.531732e-13,1.831044e-13

In [143]:
#coef_final.drop('Unnamed: 0', axis = 1, inplace = True)
#coef_final.head()
coef_5 = coef_final[['Vg', 'Temp', 'Slope_5nm', 'Inter_5nm', 'Vds_5nm']].copy()
coef_10 = coef_final[['Vg', 'Temp', 'Slope_10nm', 'Inter_10nm', 'Vds_10nm']].copy()
coef_20 = coef_final[['Vg', 'Temp', 'Slope_20nm', 'Inter_20nm', 'Vds_20nm']].copy()

In [144]:
def Extract_value(df) :
  M = 0.9
  k = 8.61733262145e-5
  epsilon_r = 7.0
  epsilon_0 = 8.8541878128e-12
  to_eV = 6.241509e18
#  permitivity = 55263499.5823

  df.columns = ['Vg', 'Temp', 'Slope', 'Inter', 'Vds']
  const = 1/(4*np.pi*epsilon_r*epsilon_0*to_eV)
  df['width'] = const/((df['Slope']*k*df['Temp']) ** 2)
  
  A = 120e-8
  M = 0.9

  df['height'] = k*df['Temp']*(np.log(A*M*(df['Temp'] ** 2)) - df['Inter'])

  return df

In [145]:
coef_5 = Extract_value(coef_5)
coef_10 = Extract_value(coef_10)
coef_20 = Extract_value(coef_20)

In [151]:
coef_20.head()

   Vg  Temp     Slope      Inter   Vds     width    height
0 -50    90  0.188196 -29.844005  high  0.000097  0.194705
1 -50   105  0.387299 -32.816569   low  0.000017  0.256842
2 -50   120  0.359692 -31.010514   low  0.000015  0.277619
3 -50   135  0.304638 -28.975344   low  0.000016  0.291386
4 -50   150  0.284700 -27.810469   low  0.000015  0.311429

In [147]:
df_20.head()

,Unnamed: 0,90,105,120,135,150,165,180,195,210,...,165.30,180.30,195.30,210.30,225.30,240.30,255.30,270.30,285.30,300.30
0,0,2.613001e-17,2.811053e-17,1.878294e-17,5.685993e-18,1.597189e-17,5.494330e-18,1.533301e-18,2.791886e-17,2.600224e-17,...,3.124102e-17,3.104935e-17,2.357451e-17,3.577703e-18,1.066922e-17,1.437470e-17,9.199808e-18,1.456636e-17,1.034978e-17,2.491615e-18
1,20,6.353694e-14,1.840953e-13,1.172707e-13,6.377549e-13,1.519884e-12,4.453417e-12,9.441501e-12,1.811356e-11,2.809758e-11,...,1.911957e-14,1.012855e-13,3.645545e-14,1.431145e-15,8.776892e-14,1.072634e-14,1.205586e-13,1.402537e-13,1.359591e-13,3.389610e-13
2,40,5.367660e-14,4.709618e-14,2.284855e-13,1.416110e-12,4.028117e-12,1.034724e-11,2.179590e-11,3.925168e-11,6.070183e-11,...,1.477669e-13,1.600434e-14,8.503747e-14,7.314033e-14,7.877163e-14,2.403105e-14,2.358536e-13,2.833873e-14,3.521885e-13,3.656348e-13
3,60,1.618930e-14,4.051385e-14,5.081765e-13,2.502685e-12,7.046869e-12,1.747149e-11,3.630870e-11,6.387985e-11,9.877706e-11,...,2.005279e-13,7.776464e-14,2.671856e-13,1.166883e-13,2.722676e-13,1.956542e-13,3.049058e-13,1.157033e-13,3.317678e-13,2.891222e-13
4,80,2.942292e-13,1.586130e-14,6.548843e-13,4.051417e-12,1.108677e-11,2.707363e-11,5.341664e-11,9.273135e-11,1.404630e-10,...,1.149688e-13,2.289936e-13,2.035521e-15,2.051203e-13,1.245187e-13,6.526402e-14,8.458464e-14,2.461957e-13,2.531732e-13,1.831044e-13

In [148]:
column_names = ['Vds']

for Vg in range (-50, -19, 1) :
  for T in range (90, 315, 15) :
    name = str(Vg) + '/' + str(T)
    column_names.append(name)

df_20.columns = column_names

df_20.set_index('Vds', inplace = True)
df_20 = df_20.transpose()

In [149]:
save_Vg_Temp = pd.DataFrame(columns = ['Vg', 'Temp'])
#print(df_5.index)
save_Vg_Temp['Vg'], save_Vg_Temp['Temp'] = df_20.index.str.split('/', 1).str
save_Vg_Temp = save_Vg_Temp.apply(pd.to_numeric)
save_Vg_Temp.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  This is separate from the ipykernel package so we can avoid doing imports until

   Vg  Temp
0 -50    90
1 -50   105
2 -50   120
3 -50   135
4 -50   150

In [150]:
df_20.reset_index(drop = True, inplace = True)
df_20.head()

Vds,0,20,40,60,80,100,120,140,160,180,...,820,840,860,880,900,920,940,960,980,1000
0,2.613001e-17,6.353694e-14,5.367660e-14,1.618930e-14,2.942292e-13,2.669839e-13,1.411662e-13,1.038448e-13,4.624264e-14,1.789261e-14,...,2.442635e-11,2.699133e-11,2.795453e-11,2.975496e-11,3.054775e-11,3.133671e-11,3.353053e-11,3.488257e-11,3.787651e-11,3.849160e-11
1,2.811053e-17,1.840953e-13,4.709618e-14,4.051385e-14,1.586130e-14,3.010293e-13,4.584870e-13,8.338280e-13,9.920088e-13,1.124345e-12,...,7.017210e-11,7.596707e-11,7.928216e-11,8.127324e-11,8.497380e-11,8.771260e-11,9.124652e-11,9.782284e-11,9.704428e-11,1.005005e-10
2,1.878294e-17,1.172707e-13,2.284855e-13,5.081765e-13,6.548843e-13,1.457892e-12,1.985328e-12,3.026689e-12,4.040007e-12,5.208836e-12,...,1.707790e-10,1.811644e-10,1.823170e-10,1.892698e-10,1.995893e-10,2.018261e-10,2.121708e-10,2.198880e-10,2.273472e-10,2.307617e-10
3,5.685993e-18,6.377549e-13,1.416110e-12,2.502685e-12,4.051417e-12,5.913706e-12,8.264745e-12,1.092477e-11,1.426198e-11,1.792923e-11,...,3.538797e-10,3.708041e-10,3.848820e-10,3.863403e-10,3.987298e-10,4.112893e-10,4.189347e-10,4.367803e-10,4.391027e-10,4.530067e-10
4,1.597189e-17,1.519884e-12,4.028117e-12,7.046869e-12,1.108677e-11,1.577890e-11,2.166774e-11,2.946289e-11,3.731478e-11,4.771852e-11,...,6.354581e-10,6.461099e-10,6.682060e-10,6.912350e-10,7.018379e-10,7.168977e-10,7.403847e-10,7.533409e-10,7.600196e-10,7.786378e-10

In [164]:
#merge_outer = pd.merge(df1,df2, how='outer',on='id')
#result3_in = pd.concat([df1,df2],axis=1, join='inner')

df_20nm = pd.concat([save_Vg_Temp, df_20], axis = 1)
df_20nm = pd.merge(df_20nm, coef_20[['Vg', 'Temp', 'Vds', 'width', 'height']], how = 'outer', on = ['Vg', 'Temp'])

In [165]:
df_20nm.head()

,Vg,Temp,0,20,40,60,80,100,120,140,...,880,900,920,940,960,980,1000,Vds,width,height
0,-50,90,2.613001e-17,6.353694e-14,5.367660e-14,1.618930e-14,2.942292e-13,2.669839e-13,1.411662e-13,1.038448e-13,...,2.975496e-11,3.054775e-11,3.133671e-11,3.353053e-11,3.488257e-11,3.787651e-11,3.849160e-11,high,0.000097,0.194705
1,-50,105,2.811053e-17,1.840953e-13,4.709618e-14,4.051385e-14,1.586130e-14,3.010293e-13,4.584870e-13,8.338280e-13,...,8.127324e-11,8.497380e-11,8.771260e-11,9.124652e-11,9.782284e-11,9.704428e-11,1.005005e-10,low,0.000017,0.256842
2,-50,120,1.878294e-17,1.172707e-13,2.284855e-13,5.081765e-13,6.548843e-13,1.457892e-12,1.985328e-12,3.026689e-12,...,1.892698e-10,1.995893e-10,2.018261e-10,2.121708e-10,2.198880e-10,2.273472e-10,2.307617e-10,low,0.000015,0.277619
3,-50,135,5.685993e-18,6.377549e-13,1.416110e-12,2.502685e-12,4.051417e-12,5.913706e-12,8.264745e-12,1.092477e-11,...,3.863403e-10,3.987298e-10,4.112893e-10,4.189347e-10,4.367803e-10,4.391027e-10,4.530067e-10,low,0.000016,0.291386
4,-50,150,1.597189e-17,1.519884e-12,4.028117e-12,7.046869e-12,1.108677e-11,1.577890e-11,2.166774e-11,2.946289e-11,...,6.912350e-10,7.018379e-10,7.168977e-10,7.403847e-10,7.533409e-10,7.600196e-10,7.786378e-10,low,0.000015,0.311429

In [166]:
df_20nm = df_20nm.replace([np.inf, -np.inf], np.nan)
df_20nm = df_20nm.dropna(axis = 0)
df_20nm

,Vg,Temp,0,20,40,60,80,100,120,140,...,880,900,920,940,960,980,1000,Vds,width,height
0,-50,90,2.613001e-17,6.353694e-14,5.367660e-14,1.618930e-14,2.942292e-13,2.669839e-13,1.411662e-13,1.038448e-13,...,2.975496e-11,3.054775e-11,3.133671e-11,3.353053e-11,3.488257e-11,3.787651e-11,3.849160e-11,high,0.000097,0.194705
1,-50,105,2.811053e-17,1.840953e-13,4.709618e-14,4.051385e-14,1.586130e-14,3.010293e-13,4.584870e-13,8.338280e-13,...,8.127324e-11,8.497380e-11,8.771260e-11,9.124652e-11,9.782284e-11,9.704428e-11,1.005005e-10,low,0.000017,0.256842
2,-50,120,1.878294e-17,1.172707e-13,2.284855e-13,5.081765e-13,6.548843e-13,1.457892e-12,1.985328e-12,3.026689e-12,...,1.892698e-10,1.995893e-10,2.018261e-10,2.121708e-10,2.198880e-10,2.273472e-10,2.307617e-10,low,0.000015,0.277619
3,-50,135,5.685993e-18,6.377549e-13,1.416110e-12,2.502685e-12,4.051417e-12,5.913706e-12,8.264745e-12,1.092477e-11,...,3.863403e-10,3.987298e-10,4.112893e-10,4.189347e-10,4.367803e-10,4.391027e-10,4.530067e-10,low,0.000016,0.291386
4,-50,150,1.597189e-17,1.519884e-12,4.028117e-12,7.046869e-12,1.108677e-11,1.577890e-11,2.166774e-11,2.946289e-11,...,6.912350e-10,7.018379e-10,7.168977e-10,7.403847e-10,7.533409e-10,7.600196e-10,7.786378e-10,low,0.000015,0.311429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,-29,285,2.932439e-17,1.602577e-13,7.086050e-14,1.068230e-13,8.890989e-14,1.206350e-13,2.800552e-13,1.116813e-13,...,2.143487e-12,2.304567e-12,2.237763e-12,2.260712e-12,2.408245e-12,2.309574e-12,2.697887e-12,high,0.000042,0.666612
329,-29,300,1.705798e-17,1.909845e-13,3.362692e-13,3.134335e-13,4.848697e-13,3.355197e-13,7.142354e-14,6.786835e-13,...,2.386474e-12,2.638500e-12,2.414405e-12,2.522024e-12,2.632084e-12,2.881899e-12,2.536498e-12,high,0.000036,0.702102
341,-28,255,9.135921e-18,1.714518e-14,1.128938e-14,3.932535e-14,1.568013e-13,7.704903e-15,1.386850e-13,5.068130e-14,...,1.232580e-12,1.565971e-12,1.545081e-12,1.553480e-12,1.582122e-12,1.540989e-12,1.608338e-12,high,0.000033,0.615758
342,-28,270,1.328861e-17,2.490294e-13,2.485715e-13,2.295360e-13,1.795042e-13,1.769266e-13,9.807833e-14,2.238812e-15,...,1.534714e-12,1.605761e-12,1.663200e-12,1.423575e-12,1.542148e-12,1.819780e-12,1.619625e-12,high,0.000037,0.644824
343,-28,285,2.938828e-18,1.371420e-13,2.971244e-14,1.183964e-15,1.769919e-13,5.001380e-14,1.213787e-13,3.360901e-14,...,1.287286e-12,1.409277e-12,1.202832e-12,1.186859e-12,1.809956e-12,1.464593e-12,1.543354e-12,high,0.000035,0.684344

In [167]:
df_20nm.to_csv('20nm')